### PR TITLE
DSND-3028: Use Intellij suggested simplification

### PR DESCRIPTION
**Pull request by sthompsonCH**
This PR was originally designed to change the order of processing so that the write to mongo during a `PUT` request was done before the invocation of chs kafka api. However, this is already the case. Therefore, I have just implemented an Intellij suggestion to simplify the delta_at evaluation logic.

[DSND-3028](https://companieshouse.atlassian.net/browse/DSND-3028)

[DSND-3028]: https://companieshouse.atlassian.net/browse/DSND-3028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by johncook-ch — APPROVED** [review]

**Review by cgregoryCH — APPROVED** [review]

**Pull request merged**
